// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'matrix.dart';

// These functions are ignored because they are not marked as `pub`: `get_authenticated_client`, `matrix_client`

Future<String> connectMatrix() =>
    RustLib.instance.api.crateApiClientConnectMatrix();

Future<AuthSession> loginMatrix({
  required String homeserver,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiClientLoginMatrix(
  homeserver: homeserver,
  username: username,
  password: password,
);

Future<void> restoreMatrixSession({
  required String homeserver,
  required String userId,
  required String deviceId,
  required String accessToken,
  String? refreshToken,
}) => RustLib.instance.api.crateApiClientRestoreMatrixSession(
  homeserver: homeserver,
  userId: userId,
  deviceId: deviceId,
  accessToken: accessToken,
  refreshToken: refreshToken,
);
