// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'matrix.dart';

// These functions are ignored because they are not marked as `pub`: `build_client`, `get_authenticated_client`, `matrix_client`, `matrix_store_path`, `matrix_sync`, `stop_matrix_sync`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SyncHandle`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `matrix_message_sender`, `subscribe_to_matrix_messages`

Future<AuthSession> loginMatrix({
  required String homeserver,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiClientLoginMatrix(
  homeserver: homeserver,
  username: username,
  password: password,
);

Future<void> restoreMatrixSession({
  required String homeserver,
  required String userId,
  required String deviceId,
  required String accessToken,
  String? refreshToken,
}) => RustLib.instance.api.crateApiClientRestoreMatrixSession(
  homeserver: homeserver,
  userId: userId,
  deviceId: deviceId,
  accessToken: accessToken,
  refreshToken: refreshToken,
);

Future<void> startMatrixSync() =>
    RustLib.instance.api.crateApiClientStartMatrixSync();

/// Encerra a sessão no homeserver, para o sync e apaga o store local.
///
/// O estado local é sempre limpo, mesmo que o homeserver esteja inacessível.
/// Nesse caso o erro do servidor é devolvido depois da limpeza.
Future<void> logoutMatrix() =>
    RustLib.instance.api.crateApiClientLogoutMatrix();

Future<void> recoverMatrixEncryption({required String recoveryKey}) => RustLib
    .instance
    .api
    .crateApiClientRecoverMatrixEncryption(recoveryKey: recoveryKey);
