// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class AuthSession {
  final String userId;
  final String deviceId;
  final String accessToken;
  final String? refreshToken;

  const AuthSession({
    required this.userId,
    required this.deviceId,
    required this.accessToken,
    this.refreshToken,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      deviceId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthSession &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken;
}
