// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<List<RoomSummary>> getRooms() =>
    RustLib.instance.api.crateApiRoomsGetRooms();

Future<MessagesPage> getMessages({required String roomId, String? fromToken}) =>
    RustLib.instance.api.crateApiRoomsGetMessages(
      roomId: roomId,
      fromToken: fromToken,
    );

Future<void> sendMessage({required String roomId, required String message}) =>
    RustLib.instance.api.crateApiRoomsSendMessage(
      roomId: roomId,
      message: message,
    );

Stream<MessageSummary> subscribeToMessages() =>
    RustLib.instance.api.crateApiRoomsSubscribeToMessages();

class MessageSummary {
  final String id;
  final String roomId;
  final String sender;
  final String content;
  final PlatformInt64 timestamp;

  const MessageSummary({
    required this.id,
    required this.roomId,
    required this.sender,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      roomId.hashCode ^
      sender.hashCode ^
      content.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          roomId == other.roomId &&
          sender == other.sender &&
          content == other.content &&
          timestamp == other.timestamp;
}

class MessagesPage {
  final List<MessageSummary> messages;
  final String? endToken;

  const MessagesPage({required this.messages, this.endToken});

  @override
  int get hashCode => messages.hashCode ^ endToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessagesPage &&
          runtimeType == other.runtimeType &&
          messages == other.messages &&
          endToken == other.endToken;
}

class RoomSummary {
  final String id;
  final String name;

  const RoomSummary({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
